[package]
name = "term-calculator"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "term/src/main.rs"
name = "term"

[dependencies]
calculate = {path = "calculate"}
home = "0.5.3"

[workspace]
members = [
    "calculate",
    "term",
    #"wasm"
]