[package]
name = "calculate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = { version = "0.7.3", default-features = false, features = ["parse"] }
serde = { version = "1.0.157", features = ["derive"] }